name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: install mkdocs
        run: pip install mkdocs-material 
      
      - name: install tooltips
        run: pip install mkdocs-tooltips

      - name: install minify plugin
        run: pip install mkdocs-minify-plugin

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          CONFIG_FILE: /mkdocs.yml
          EXTRA_PACKAGES: build-base