name: deployment 
on:
  push:
    branches: 
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-tooltips
      - run: pip install mkdocs-minify-plugin
      - run: mkdocs gh-deploy --force
